import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace DirectionalDataSpatialStatisticsCanonicalLaneLean

end DirectionalDataSpatialStatisticsCanonicalLaneLean
end HautevilleHouse
